apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-api
  namespace: airflow
spec:
  ingressClassName: traefik
  rules:
    - host: airflow.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-api-server
                port:
                  number: 8080
